# Model arguments
model_name_or_path: UCLA-AGI/Gemma-2-9B-It-SPPO-Iter3
torch_dtype: null
trust_remote_code: true

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  USERNAME/ultrafeedback_reward_augmented_nosys: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12
auto_insert_empty_system_msg: false

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: sppo-dpo-ra
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: data/sppo-dpo-ra
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
push_to_hub: false
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1